Search input width is same as parent div.
chihacknight/ghost-buses-frontend pull request #48
Opened 2022-12-13 10:02 UTC by Rishav1707

### This PR fixes the following issues:-
closes #45 
### Changes made:-

- Replacing the padding property from 10px to 15px.
- Adding the margin-left property.
### Screenshots:-
### Before
 
![207106190-8ac9af98-7518-47fa-861a-e83dc10e1a76](https://user-images.githubusercontent.com/97666287/207287480-df6dfb4f-1aa4-4184-b127-925c231a3cd3.png)
### After
![WhatsApp Image 2022-12-13 at 3 18 11 PM](https://user-images.githubusercontent.com/97666287/207287524-551c9154-5555-4a23-8e50-c60c549c577d.jpeg)

2022-12-14 02:49 UTC, amy-corson requested changes
Hi Rishav! First of all, thanks so much for contributing to this project! We're really excited to have you onboard.

This solution is a little off the mark, so I just wanted to point out a few things that will help you fix this issue. 

1) You've targeted the right selector in CSS, but we're using SCSS to compile our CSS file, so you'll need to add these changes into the SCSS file and then use an extension such as Live Sass Compiler.
2) You're adding `padding` and a `margin-left` to the search bar, which is essentially adding pixels to all four sides and pushing it 2 pixels to the right. And while this may look okay on smaller screens, it's not showing up as the full width across the board. I would recommend targeting the input's `width` and try setting it according to the width of the parent container.
<img width="278" alt="Screen Shot 2022-12-13 at 8 37 30 PM" src="https://user-images.githubusercontent.com/92054473/207493022-797803ee-8db2-4aa7-a719-d9af2b308f8b.png">

2022-12-15 13:02 UTC, Rishav1707 commented
> Hi Rishav! First of all, thanks so much for contributing to this project! We're really excited to have you onboard.
> 
> This solution is a little off the mark, so I just wanted to point out a few things that will help you fix this issue.
> 
> 1. You've targeted the right selector in CSS, but we're using SCSS to compile our CSS file, so you'll need to add these changes into the SCSS file and then use an extension such as Live Sass Compiler.
> 2. You're adding `padding` and a `margin-left` to the search bar, which is essentially adding pixels to all four sides and pushing it 2 pixels to the right. And while this may look okay on smaller screens, it's not showing up as the full width across the board. I would recommend targeting the input's `width` and try setting it according to the width of the parent container.
> 
> <img alt="Screen Shot 2022-12-13 at 8 37 30 PM" width="278" src="https://user-images.githubusercontent.com/92054473/207493022-797803ee-8db2-4aa7-a719-d9af2b308f8b.png">

Done @amy-corson 
![WhatsApp Image 2022-12-15 at 6 19 45 PM](https://user-images.githubusercontent.com/97666287/207865433-5c3c4af4-6454-4b87-b1cd-ac70bc86a746.jpeg)

2022-12-16 10:12 UTC, Rishav1707 commented
@amy-corson Please review my changes...

2022-12-17 12:04 UTC, Rishav1707 commented
> @amy-corson Please review my changes...

Anyone is there?? @amy-corson

2022-12-17 13:38 UTC, amy-corson commented
> > @amy-corson Please review my changes...
> 
> Anyone is there?? @amy-corson

@Rishav1707  Hello! I do not work on this project full time. I see your pull request, I will review it when I get the chance. No need to keep tagging me. Thanks for your patience!

2022-12-17 13:41 UTC, Rishav1707 commented
> > > @amy-corson Please review my changes...
> > 
> > 
> > Anyone is there?? @amy-corson
> 
> @Rishav1707 Hello! I do not work on this project full time. I see your pull request, I will review it when I get the chance. Thanks for your patience!

OK

2023-01-04 00:16 UTC, amy-corson reviewed
This is closer! I recommended a few tweaks, but if you can add those changes you should be good to merge. Thanks so much!

2023-01-04 00:16 UTC, amy-corson commented on src/scss/_search.scss
> +      padding: 15px;
I would remove this, as the padding does not need to change for this fix.

2023-01-04 00:16 UTC, amy-corson commented on src/scss/_search.scss
> +      width: 85%;
This is really close! I would actually recommend a fix closer to: 
```
width: 100%;
box-sizing: border-box;
```
The width will make sure the input fills the entire parent container, and the box-sizing attribute will make sure it does not overflow.

Let me know if you have questions, and thanks for contributing

2023-01-22 21:02 UTC, amy-corson reviewed
Hello! Thanks for your changes on this. The SCSS needs to be compiled into CSS for this change to take effect. You can use a compiler such as Watch Sass for this, or if you'd like I can add a commit to your branch. Let me know which one you'd prefer!

2023-01-23 04:06 UTC, Rishav1707 commented
> Hello! Thanks for your changes on this. The SCSS needs to be compiled into CSS for this change to take effect. You can use a compiler such as Watch Sass for this, or if you'd like I can add a commit to your branch. Let me know which one you'd prefer!

Sure, you can add a commit in this branch

2023-03-08 02:30 UTC, amy-corson approved these changes
Hello! this is good to merge. Apologies for the delay in getting back to you. You can ignore the substantial diff, my formatter went a little crazy

2023-03-12 14:31 UTC, Rishav1707 commented
When this PR get merged?

2023-03-15 00:01 UTC, merged

2023-03-15 00:01 UTC, amy-corson commented
Thanks for the help!