[Issue#47] Fix alignment of block quote
chihacknight/ghost-buses-frontend pull request #51
Opened 2023-01-04 01:41 UTC by KyleDolezal

**Overview**
This PR addresses a concern around the appearance of the block quote by changing the justification of block quotes.

**Problem**
The alignment of the block quote is looking a little wonky on smaller screen sizes.

**Solution**
Change the justification for the block quote from right justified to left justified.

2023-01-22 20:59 UTC, amy-corson requested changes
Hello! We use SCSS compiled in to CSS for this project, so the SCSS file for the header will need to be changed, and you can use an extension such as `Watch Sass` to compile! If you can update the scss, change should be good to go! Let me know if you have questions

2023-02-01 02:08 UTC, KyleDolezal commented
> Hello! We use SCSS compiled in to CSS for this project, so the SCSS file for the header will need to be changed, and you can use an extension such as `Watch Sass` to compile! If you can update the scss, change should be good to go! Let me know if you have questions

Thanks for the tip! I tried to make the change via scss. Just let me know if there's any other ideas.

2023-05-10 02:18 UTC, amy-corson approved these changes
Looks good, just one quick question on a comment within the css file. 

And I'm so sorry for the late late late review!

2023-05-10 02:18 UTC, amy-corson commented on src/css/main.css
> +/*# sourceMappingURL=main.css.map */
hmm what's this guy doing down here! Can this be safely removed?

2023-07-20 03:53 UTC, hkier commented
It appears this PR is capturing the update to main.css after scss compiles the file.  I think we can ignore the change to the main.css file but I have to double check.

2023-07-20 23:56 UTC, hkier commented
I have taken a close look at the PR and discovered it is actually 1 commit ahead and 39 commits behind main.  The easiest way to fix the problem is to close this PR, create a new branch with the change and then merge it into main.

2023-07-21 00:00 UTC, hkier commented
out of date

2023-07-21 00:00 UTC, closed without merging