Map legend restyling
chihacknight/ghost-buses-frontend pull request #56
Opened 2023-01-27 04:44 UTC by smacmullan

Recolored the map legend and changed the legend labels.

2023-02-03 02:20 UTC, lauriemerrell commented
Just adding a comment I made in Slack for visibility -- I love the legend phrasing and reordering the colors, but I *think* we may want to stick with a blue/orange color scale rather than blue/red for better accessibility for colorblind users. I would defer to @amy-corson though who has done more research on this!

2023-02-08 02:14 UTC, amy-corson requested changes
Hello! First of all, thank you SO MUCH for taking the initiative to address this! I really love the labeling changes in the key, and I agree strongly that this language is so much easier to understand! There are two things I'd like to discuss/address in this PR:
- I personally would want to see the colors reverted to the yellow/purple heatmap, because I think i value the color contrast over trying to assign colors with more positive/negative connotations. Open to discussing this more, I know we've got a Slack thread going.
- This project uses an SCSS compiler, so ideally you would be making these changes in the SCSS files not editing directly, while also using an extension such as live sass compiler! (this is such a terrible system we need to update it.)

2023-02-08 02:14 UTC, amy-corson commented on src/css/main.css
> +}
per above note, if we keep the `flex` over the `grid`, just add a `width: 100%` here to get the `text-align` to work!

2023-02-09 02:34 UTC, smacmullan commented
I switched to a yellow-purple gradient. I'm not sure if you were asking for the original color scheme? In the Slack thread we were discussing use a two-color gradient because it's easier to interpret hot and cold on the heat map.

2023-02-09 02:56 UTC, smacmullan commented
I got sass working. If you make changes to scss files while running "npm start", changes will auto-update.

2023-03-04 18:34 UTC, amy-corson commented
@smacmullan Can you update the PR description to outline both of the packages you're adding, what they do, and why they're necessary?

2023-03-06 04:23 UTC, smacmullan commented
I changed the description. Unless I'm missing something, I've only add the one package: sass.

2023-03-08 02:40 UTC, smacmullan commented
Immutable is a sass dependency (shows up in the package-lock).

2023-03-08 02:57 UTC, amy-corson approved these changes
LGTM! Thanks so much!

2023-03-08 03:53 UTC, merged